sudo: false
language: rust
rust:
 - stable
 - beta
 - nightly
os:
 - linux
 - osx
matrix:
  allow_failures:
   - rust: nightly
  exclude:
   - os: osx
     rust: nightly
   - os: osx
     rust: beta
addons:
  apt:
    packages:
     - unixodbc
     - unixodbc-dev
services:
 - postgresql