sudo: false
language: rust
rust:
 - stable
 - beta
 - nightly
os:
 - linux
 - osx
env:
  - FLAGS=
  - FLAGS=--features static

matrix:
  allow_failures:
   - rust: nightly
  exclude:
   - os: osx
     rust: nightly
   - os: osx
     rust: beta
before_install: |
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    brew install unixodbc
  fi
addons:
  apt:
    packages:
     - unixodbc
     - unixodbc-dev
services:
 - postgresql