sudo: false
dist: bionic
language: rust
rust:
 - stable
 - beta
 - nightly
os:
 - linux
 - osx
env:
  - FLAGS=
  - FLAGS="--features static" ODBC_SYS_STATIC_PATH=/usr/lib/x86_64-linux-gnu/

script:
  - cargo build --verbose --all $FLAGS
  - cargo test --verbose --all $FLAGS

matrix:
  allow_failures:
   - rust: nightly
  exclude:
   - os: osx
     rust: nightly
   - os: osx
     rust: beta
before_install: |
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    HOMEBREW_NO_AUTO_UPDATE=1 brew install unixodbc
  fi
addons:
  apt:
    packages:
     - unixodbc
     - unixodbc-dev
services:
 - postgresql