[package]
name = "odbc-ffi"
version = "0.2.4"
authors = ["Markus Klein <markus-klein@live.de>"]
license = "MIT"
description = "renamed to odbc-sys"
repository = "https://github.com/pacman82/odbc-ffi"
documentation = "https://docs.rs/odbc-ffi/"
readme = "README.md"
keywords = ["sql","database","odbc","ffi"]
build = "build.rs"
categories = ["external-ffi-bindings", "database"]

[dependencies]

[features]
default = ["odbc_version_3_80"]

odbc_version_3_50 = []
odbc_version_3_80 = ["odbc_version_3_50"]
odbc_version_4 = ["odbc_version_3_80"]

[badges]
travis-ci = { repository = "https://github.com/pacman82/odbc-ffi", branch = "master" }
