[package]
name = "odbc-ffi"
version = "0.2.2"
authors = ["Markus Klein <markus-klein@live.de>"]
license = "MIT"
description = "ffi bindings to odbc"
repository = "https://github.com/pacman82/odbc-ffi"
documentation = "https://docs.rs/odbc-ffi/"
readme = "README.md"
keywords = ["sql","database","odbc","ffi"]
<<<<<<< HEAD
categories = ["database", "api-bindings", "external-ffi-bindings"]
build = "build.rs"
=======
categories = ["external-ffi-bindings", "database"]

>>>>>>> 2ad408b03197acd218228258ae65868c7be1df95

[dependencies]

[features]
default = ["odbc_version_3_80"]

odbc_version_3_80 = []
odbc_version_4 = ["odbc_version_3_80"]

[badges]
travis-ci = { repository = "https://github.com/pacman82/odbc-ffi", branch = "master" }
